# Dockerfile: solely responsible for runtime instantiation and dependency installation for the API
FROM python:latest AS run

RUN apt-get update && \
    apt-get upgrade -y;

# RUN pip install --upgrade pip

WORKDIR /src
COPY ./requirements.txt /src

RUN pip install --no-cache-dir --upgrade -r requirements.txt
